# To run Ts2Vec model with the pipeline integration on classification tasks for multivariate time series
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset ArticularyWordRecognition
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset AtrialFibrillation
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset BasicMotions
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset CharacterTrajectories
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset Cricket
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset DuckDuckGeese
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset EigenWorms
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset Epilepsy
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset ERing
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset EthanolConcentration
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset FaceDetection
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset FingerMovements
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset HandMovementDirection
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset Handwriting
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset Heartbeat
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset JapaneseVowels
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset Libras
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset LSST
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset MotorImagery
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset NATOPS
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset PEMS-SF
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset PenDigits
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset PhonemeSpectra
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset RacketSports
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset SelfRegulationSCP1
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset SelfRegulationSCP2
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset SpokenArabicDigits
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset StandWalkJump
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset UWaveGestureLibrary
python3 script_classification.py --mode ts2vec-dlinear-one-loss  --loader UEA --dataset InsectWingbeat

#To run original Ts2Vec model on classification task for multivariate time series
python3 script_classification.py --mode ts2vec  --loader UEA --dataset ArticularyWordRecognition
python3 script_classification.py --mode ts2vec  --loader UEA --dataset AtrialFibrillation
python3 script_classification.py --mode ts2vec  --loader UEA --dataset BasicMotions
python3 script_classification.py --mode ts2vec  --loader UEA --dataset CharacterTrajectories
python3 script_classification.py --mode ts2vec  --loader UEA --dataset Cricket
python3 script_classification.py --mode ts2vec  --loader UEA --dataset DuckDuckGeese
python3 script_classification.py --mode ts2vec  --loader UEA --dataset EigenWorms
python3 script_classification.py --mode ts2vec  --loader UEA --dataset Epilepsy
python3 script_classification.py --mode ts2vec  --loader UEA --dataset ERing
python3 script_classification.py --mode ts2vec  --loader UEA --dataset EthanolConcentration
python3 script_classification.py --mode ts2vec  --loader UEA --dataset FaceDetection
python3 script_classification.py --mode ts2vec  --loader UEA --dataset FingerMovements
python3 script_classification.py --mode ts2vec  --loader UEA --dataset HandMovementDirection
python3 script_classification.py --mode ts2vec  --loader UEA --dataset Handwriting
python3 script_classification.py --mode ts2vec  --loader UEA --dataset Heartbeat
python3 script_classification.py --mode ts2vec  --loader UEA --dataset JapaneseVowels
python3 script_classification.py --mode ts2vec  --loader UEA --dataset Libras
python3 script_classification.py --mode ts2vec  --loader UEA --dataset LSST
python3 script_classification.py --mode ts2vec  --loader UEA --dataset MotorImagery
python3 script_classification.py --mode ts2vec  --loader UEA --dataset NATOPS
python3 script_classification.py --mode ts2vec  --loader UEA --dataset PEMS-SF
python3 script_classification.py --mode ts2vec  --loader UEA --dataset PenDigits
python3 script_classification.py --mode ts2vec  --loader UEA --dataset PhonemeSpectra
python3 script_classification.py --mode ts2vec  --loader UEA --dataset RacketSports
python3 script_classification.py --mode ts2vec  --loader UEA --dataset SelfRegulationSCP1
python3 script_classification.py --mode ts2vec  --loader UEA --dataset SelfRegulationSCP2
python3 script_classification.py --mode ts2vec  --loader UEA --dataset SpokenArabicDigits
python3 script_classification.py --mode ts2vec  --loader UEA --dataset StandWalkJump
python3 script_classification.py --mode ts2vec  --loader UEA --dataset UWaveGestureLibrary
python3 script_classification.py --mode ts2vec  --loader UEA --dataset InsectWingbeat